version: 2 # use CircleCI 2.0
jobs: # a collection of jobs
  build: 
    docker: # run build steps with docker
      - image: crystallang/crystal:0.34.0 # primary docker container; all `steps` will run here.
    steps: # a collection of executable steps
      - checkout # checks out source code to working directory
      - restore_cache: # Restore dependency cache
          key: dependency-cache-{{ checksum "shard.lock" }}
      - run:
          name: Install dependencies.
          command: shards install
      - save_cache:
          key: dependency-cache-{{ checksum "shard.lock" }}
          paths:
            - ./lib
      #- run:
          #name: Install cmake
          #command: sed -i -- 's/VERSION 3.13/VERSION 3.5/g' CMakeLists.txt && apt update && apt search cmake && apt-get install -y cmake
      - run:
          name: Update submodules
          command: git submodule update --init
      #- run:
          #name: Build evmone
          #command: mkdir -p build/evmone && cd build/evmone && cmake ../../evmone && cmake --build . -- -j
      - run:
          name: test
          command: crystal spec --error-trace
